// Creado por Diego Castro
// Archivo temporal que simula la respuesta del API de historial académico
// Reemplazar por el fetch() real cuando el API esté disponible

export interface Nivel {
  appliedLevel: string;
  levelDescription: string;
  primaryLevel: string;
}

export interface CursoHistorial {
  id: string;
  bannerId: string;
  activityAcademic: string;
  courseIdentifierDisplay: string;
  courseNumber: string;
  courseReferenceNumber: string;
  courseSequenceNumber: number;
  courseTitle: string;
  subject: string;
  subjectDescription: string;
  term: string;
  termDescription: string;
  studyPathSequenceNumber: number;
  attemptedHours?: number;
  creditHours?: number;
  grade: string;
  mode: string;
  modeDescription: string;
  sequenceNumber: number;
  courseLongTitle: string;
  levels: Nivel[];
}

export interface HistorialAcademicoResponse {
  status: number;
  message: string;
  response: CursoHistorial[];
}

export interface FilaHistorial {
  codigoEstudiante: string;
  anio: string;
  periodo: string;
  cursoCodigo: string;
  cursoNombre: string;
  calificacion: string;
  letra: string;
  creditos: string;
}

// Mapear los datos que vienen de la respuesta
export function mapearCurso(curso: FilaHistorial): FilaHistorial {
  return {
    codigoEstudiante: curso.codigoEstudiante,
    anio: curso.anio,
    periodo: curso.periodo,
    cursoCodigo: curso.cursoCodigo,
    cursoNombre: curso.cursoNombre,
    calificacion: curso.calificacion,
    letra: curso.letra,
    creditos: curso.creditos,
  };
}

export const HistorialAcademico: HistorialAcademicoResponse = {
  status: 200,
  message: "Historial académico obtenido exitosamente",
  response: [
    {
      id: "d6312b67-e4c8-47c7-84e2-1e0f52ed7a44",
      bannerId: "28300",
      activityAcademic: "AH1011",
      courseIdentifierDisplay: "APRENDER HACIENDO I",
      courseNumber: "1011",
      courseReferenceNumber: "SG001",
      courseSequenceNumber: 1.0,
      courseTitle: "AH1011-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 7.0,
      creditHours: 7.0,
      grade: "56.00", //Originalmente 96.00
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "APRENDER HACIENDO I",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "08853655-f21d-491c-b778-645244d55b6f",
      bannerId: "28300",
      activityAcademic: "AH1004",
      courseIdentifierDisplay: "PROD GRANOS SEMILLAS",
      courseNumber: "1004",
      courseReferenceNumber: "SG002",
      courseSequenceNumber: 2.0,
      courseTitle: "AH1004-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "96.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PRODUCCION DE GRANOS Y SEMILLAS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "4271e453-8e30-4a4a-8c7e-87f84d073d31",
      bannerId: "28300",
      activityAcademic: "AH1003",
      courseIdentifierDisplay: "PLA ALIM CONCETRADOS",
      courseNumber: "1003",
      courseReferenceNumber: "SG003",
      courseSequenceNumber: 3.0,
      courseTitle: "AH1003-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "97.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PLANTA DE ALIMENTOS CONCENTRADOS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "ebcad498-076d-4773-a2d9-21a1367d6602",
      bannerId: "28300",
      activityAcademic: "AH1002",
      courseIdentifierDisplay: "PLANTA DE SEMILLAS",
      courseNumber: "1002",
      courseReferenceNumber: "SG004",
      courseSequenceNumber: 4.0,
      courseTitle: "AH1002-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "95.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PLANTA DE SEMILLAS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "fd87c1cd-c247-43ca-a5a0-2437da1f46c2",
      bannerId: "28300",
      activityAcademic: "AH1001",
      courseIdentifierDisplay: "PROPAGACION PLANTAS",
      courseNumber: "1001",
      courseReferenceNumber: "SG005",
      courseSequenceNumber: 5.0,
      courseTitle: "AH1001-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "95.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PROPAGACION DE PLANTAS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "8a4bb715-7d04-450a-900c-7b9e793257a7",
      bannerId: "28300",
      activityAcademic: "CG1163",
      courseIdentifierDisplay: "SOCIOLOGIA",
      courseNumber: "1163",
      courseReferenceNumber: "SG006",
      courseSequenceNumber: 6.0,
      courseTitle: "CG1163-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "90.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "SOCIOLOGIA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "6523bfaf-5822-4368-bb71-e8d365b33e5a",
      bannerId: "28300",
      activityAcademic: "CG1021",
      courseIdentifierDisplay: "ALGEBRA LINEAL",
      courseNumber: "1021",
      courseReferenceNumber: "SG007",
      courseSequenceNumber: 7.0,
      courseTitle: "CG1021-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "ALGEBRA LINEAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "49d75819-8c49-426e-8e58-e526a8175d5c",
      bannerId: "28300",
      activityAcademic: "CG1031",
      courseIdentifierDisplay: "ESPAÑOL I",
      courseNumber: "1031",
      courseReferenceNumber: "SG008",
      courseSequenceNumber: 8.0,
      courseTitle: "CG1031-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "ESPAÑOL I",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "cbfa9c8d-54ec-4e79-b381-fd56debfe458",
      bannerId: "28300",
      activityAcademic: "CG1041",
      courseIdentifierDisplay: "ING I COMUNIC BASICA",
      courseNumber: "1041",
      courseReferenceNumber: "SG009",
      courseSequenceNumber: 9.0,
      courseTitle: "CG1041-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 2.0,
      creditHours: 2.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "INGLES I COMUNICACION BASICA ORAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "64119076-5a75-4d5b-b50a-1aeaed3bce41",
      bannerId: "28300",
      activityAcademic: "CG1061",
      courseIdentifierDisplay: "QUIMICA GENERAL",
      courseNumber: "1061",
      courseReferenceNumber: "SG010",
      courseSequenceNumber: 10.0,
      courseTitle: "CG1061-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "89.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "QUIMICA GENERAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "88a9e713-33ba-41ac-a9f9-d8f9b11dcf50",
      bannerId: "28300",
      activityAcademic: "CG1011",
      courseIdentifierDisplay: "BIO FISIOLOG CELULAR",
      courseNumber: "1011",
      courseReferenceNumber: "SG011",
      courseSequenceNumber: 11.0,
      courseTitle: "CG1011-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202510",
      termDescription: "PERIODO 2025 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 4.0,
      creditHours: 4.0,
      grade: "88.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "BIOLOGIA Y FISIOLOGIA CELULAR",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "244b63ac-6fc0-4058-8f2f-830beca035d9",
      bannerId: "28300",
      activityAcademic: "AH1022",
      courseIdentifierDisplay: "APRENDER HACIENDO II",
      courseNumber: "1022",
      courseReferenceNumber: "SG001",
      courseSequenceNumber: 1.0,
      courseTitle: "AH1022-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 7.0,
      creditHours: 7.0,
      grade: "95.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "APRENDER HACIENDO II",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "04fbb32d-6862-47a9-90a6-1b1c20bdbf4f",
      bannerId: "28300",
      activityAcademic: "AH1018",
      courseIdentifierDisplay: "MANEJO FORESTAL",
      courseNumber: "1018",
      courseReferenceNumber: "SG002",
      courseSequenceNumber: 2.0,
      courseTitle: "AH1018-2-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      grade: "98.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "MANEJO FORESTAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "fd4ad8b0-946b-4116-af86-ce76d1c25cb6",
      bannerId: "28300",
      activityAcademic: "AH1017",
      courseIdentifierDisplay: "PLANTACIO FORESTALES",
      courseNumber: "1017",
      courseReferenceNumber: "SG003",
      courseSequenceNumber: 3.0,
      courseTitle: "AH1017-2-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PLANTACIONES FORESTALES",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "59e0cda5-6d34-426b-ad8b-7d81bd189daa",
      bannerId: "28300",
      activityAcademic: "AH1016",
      courseIdentifierDisplay: "VALO AGREGADO MADERA",
      courseNumber: "1016",
      courseReferenceNumber: "SG004",
      courseSequenceNumber: 4.0,
      courseTitle: "AH1016-2-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      grade: "93.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "VALOR AGREGADO DE LA MADERA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "5365b4b8-82e2-4435-a050-225ad06bd27b",
      bannerId: "28300",
      activityAcademic: "AH1014",
      courseIdentifierDisplay: "AGRICUL REGENERATIVA",
      courseNumber: "1014",
      courseReferenceNumber: "SG005",
      courseSequenceNumber: 5.0,
      courseTitle: "AH1014-2-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      grade: "89.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "AGRICULTURA REGENERATIVA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "5320e89a-93f1-4881-b5de-315402c8f003",
      bannerId: "28300",
      activityAcademic: "CG1072",
      courseIdentifierDisplay: "BIOLOGIA ORGANISMOS",
      courseNumber: "1072",
      courseReferenceNumber: "SG006",
      courseSequenceNumber: 6.0,
      courseTitle: "CG1072-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 4.0,
      creditHours: 4.0,
      grade: "91.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "BIOLOGIA DE ORGANISMOS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "17522728-0665-45ef-b44a-b4f3606aaf1d",
      bannerId: "28300",
      activityAcademic: "CG1122",
      courseIdentifierDisplay: "ESPAÑOL II",
      courseNumber: "1122",
      courseReferenceNumber: "SG007",
      courseSequenceNumber: 7.0,
      courseTitle: "CG1122-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "ESPAÑOL II",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "ea71154d-55ad-428a-aad8-ea626e7cb74c",
      bannerId: "28300",
      activityAcademic: "CG1112",
      courseIdentifierDisplay: "HISTORIA DE HONDURAS",
      courseNumber: "1112",
      courseReferenceNumber: "SG008",
      courseSequenceNumber: 8.0,
      courseTitle: "CG1112-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "98.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "HISTORIA DE HONDURAS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "eca1386a-7890-484c-8a9b-341012020e0c",
      bannerId: "28300",
      activityAcademic: "CG1102",
      courseIdentifierDisplay: "ING II COMUNI BASICA",
      courseNumber: "1102",
      courseReferenceNumber: "SG009",
      courseSequenceNumber: 9.0,
      courseTitle: "CG1102-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 2.0,
      creditHours: 2.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "INGLES II COMUNICACION BASICA ORAL Y ESCRITA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "32c792de-3f44-4d12-b036-25824888810b",
      bannerId: "28300",
      activityAcademic: "CG1092",
      courseIdentifierDisplay: "QUIMICA INORGANICA",
      courseNumber: "1092",
      courseReferenceNumber: "SG010",
      courseSequenceNumber: 10.0,
      courseTitle: "CG1092-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "QUIMICA INORGANICA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "78f869e8-78ed-4106-b800-57ed9351e4c1",
      bannerId: "28300",
      activityAcademic: "CG1082",
      courseIdentifierDisplay: "PRECALCULO",
      courseNumber: "1082",
      courseReferenceNumber: "SG011",
      courseSequenceNumber: 11.0,
      courseTitle: "CG1082-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202520",
      termDescription: "PERIODO 2025 - C2",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 4.0,
      creditHours: 4.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PRECALCULO",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "c91cd8b0-8855-4634-9b65-ea1c7c1956eb",
      bannerId: "28300",
      activityAcademic: "AH1005",
      courseIdentifierDisplay: "MAQUINARIA AGRICOLA",
      courseNumber: "1005",
      courseReferenceNumber: "SG001",
      courseSequenceNumber: 1.0,
      courseTitle: "AH1005-3-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "MAQUINARIA AGRICOLA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "a72917dc-3d16-4fc8-aac0-2a4913f74ef6",
      bannerId: "28300",
      activityAcademic: "AH1006",
      courseIdentifierDisplay: "RIEGO Y DRENAJE",
      courseNumber: "1006",
      courseReferenceNumber: "SG002",
      courseSequenceNumber: 2.0,
      courseTitle: "AH1006-3-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      grade: "94.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "RIEGO Y DRENAJE",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "226a33e0-093c-4f73-89d8-d90de80a39ef",
      bannerId: "28300",
      activityAcademic: "AH1009",
      courseIdentifierDisplay: "CONSER MANEJO SUELOS",
      courseNumber: "1009",
      courseReferenceNumber: "SG003",
      courseSequenceNumber: 3.0,
      courseTitle: "AH1009-3-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      grade: "97.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "CONSERVACION Y MANEJO DE SUELOS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "0db56951-53d4-4343-8f39-27b952ffcf7d",
      bannerId: "28300",
      activityAcademic: "AH1012",
      courseIdentifierDisplay: "PRO GRANO CON HUMANO",
      courseNumber: "1012",
      courseReferenceNumber: "SG004",
      courseSequenceNumber: 4.0,
      courseTitle: "AH1012-3-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PROCESAMIENTO DE GRANOS PARA CONSUMO HUMANO",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "d9e6dd07-f9f4-4823-b875-9ec6cf39a1a2",
      bannerId: "28300",
      activityAcademic: "AH1033",
      courseIdentifierDisplay: "APRENDE HACIENDO III",
      courseNumber: "1033",
      courseReferenceNumber: "SG005",
      courseSequenceNumber: 5.0,
      courseTitle: "AH1033-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 7.0,
      creditHours: 7.0,
      grade: "97.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "APRENDER HACIENDO III",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "bac8952d-4faf-4a93-a5aa-34ebce7f599d",
      bannerId: "28300",
      activityAcademic: "IAD1013",
      courseIdentifierDisplay: "ECOLOGIA",
      courseNumber: "1013",
      courseReferenceNumber: "SG006",
      courseSequenceNumber: 6.0,
      courseTitle: "IAD1013-ASIGNATU",
      subject: "IAD",
      subjectDescription: "AMBIENTE Y DESARROLLO",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "90.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "ECOLOGIA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "7073968a-6399-4aa8-871e-a8e09cc9b04f",
      bannerId: "28300",
      activityAcademic: "CG1153",
      courseIdentifierDisplay: "ING III COMUNI INTEG",
      courseNumber: "1153",
      courseReferenceNumber: "SG007",
      courseSequenceNumber: 7.0,
      courseTitle: "CG1153-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 2.0,
      creditHours: 2.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "INGLES III COMUNICACION INTEGRADA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "ffe42bed-d572-40d4-90ea-c160f77e8898",
      bannerId: "28300",
      activityAcademic: "CG1143",
      courseIdentifierDisplay: "QUIMICA ORGANICA",
      courseNumber: "1143",
      courseReferenceNumber: "SG008",
      courseSequenceNumber: 8.0,
      courseTitle: "CG1143-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "91.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "QUIMICA ORGANICA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "b5327958-2b6f-4196-bdd1-966f7f7c201f",
      bannerId: "28300",
      activityAcademic: "CG1133",
      courseIdentifierDisplay: "CALCULO DIFERENCIAL",
      courseNumber: "1133",
      courseReferenceNumber: "SG009",
      courseSequenceNumber: 9.0,
      courseTitle: "CG1133-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "96.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "CALCULO DIFERENCIAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "79f4362c-1bdc-433f-9ae0-522aa51c9b5f",
      bannerId: "28300",
      activityAcademic: "CG1051",
      courseIdentifierDisplay: "FILOSOFIA",
      courseNumber: "1051",
      courseReferenceNumber: "SG010",
      courseSequenceNumber: 10.0,
      courseTitle: "CG1051-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "FILOSOFIA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "dd577dfc-1d94-4752-a776-755902bbff76",
      bannerId: "28300",
      activityAcademic: "CPA1013",
      courseIdentifierDisplay: "PRODUCCION VEGETAL",
      courseNumber: "1013",
      courseReferenceNumber: "SG011",
      courseSequenceNumber: 11.0,
      courseTitle: "CPA1013-ASIGNATU",
      subject: "CPA",
      subjectDescription: "CIENCIA PRODUC AGROPECUARIA",
      term: "202530",
      termDescription: "PERIODO 2025 - C3",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 4.0,
      creditHours: 4.0,
      grade: "90.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "PRODUCCION VEGETAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "9759dbd6-abbd-4e18-a569-71d3370e94a4",
      bannerId: "28300",
      activityAcademic: "CG2181",
      courseIdentifierDisplay: "BIOQUIMICA",
      courseNumber: "2181",
      courseReferenceNumber: "SG001",
      courseSequenceNumber: 1.0,
      courseTitle: "CG2181-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "95.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "BIOQUIMICA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "a70b1e3d-6f71-436c-a8fc-826c18a856c9",
      bannerId: "28300",
      activityAcademic: "CG2191",
      courseIdentifierDisplay: "CALCULO INTEGRAL",
      courseNumber: "2191",
      courseReferenceNumber: "SG002",
      courseSequenceNumber: 2.0,
      courseTitle: "CG2191-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 4.0,
      creditHours: 4.0,
      grade: "96.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "CALCULO INTEGRAL",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "fbdc8da2-ebe9-411f-aa74-aaf9341b3dff",
      bannerId: "28300",
      activityAcademic: "CPA2021",
      courseIdentifierDisplay: "SUELOS",
      courseNumber: "2021",
      courseReferenceNumber: "SG003",
      courseSequenceNumber: 3.0,
      courseTitle: "CPA2021-ASIGNATU",
      subject: "CPA",
      subjectDescription: "CIENCIA PRODUC AGROPECUARIA",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "93.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "SUELOS",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "fb6c0bf1-43b5-4b22-9777-7ef9ac769181",
      bannerId: "28300",
      activityAcademic: "AH2009",
      courseIdentifierDisplay: "CONTROL BIOLOGICO",
      courseNumber: "2009",
      courseReferenceNumber: "SG004",
      courseSequenceNumber: 4.0,
      courseTitle: "AH2009-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "99.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "CONTROL BIOLOGICO",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "8a591c27-59db-4b40-9702-7ae100c8d65e",
      bannerId: "28300",
      activityAcademic: "AH2041",
      courseIdentifierDisplay: "APRENDER HACIENDO IV",
      courseNumber: "2041",
      courseReferenceNumber: "SG005",
      courseSequenceNumber: 5.0,
      courseTitle: "AH2041-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 7.0,
      creditHours: 7.0,
      grade: "98.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "APRENDER HACIENDO IV",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "50216e2a-5a40-4bae-90d2-56e4c09be32d",
      bannerId: "28300",
      activityAcademic: "AH2027",
      courseIdentifierDisplay: "TECNOLOGIAS AMBIENTALES",
      courseNumber: "2027",
      courseReferenceNumber: "SG006",
      courseSequenceNumber: 6.0,
      courseTitle: "AH2027-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "TECNOLOGIAS AMBIENTALES",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "a998f8ae-d952-40dc-822d-deba931315cc",
      bannerId: "28300",
      activityAcademic: "AH2025",
      courseIdentifierDisplay: "CUL TEJ DIAG MOLECUL",
      courseNumber: "2025",
      courseReferenceNumber: "SG007",
      courseSequenceNumber: 7.0,
      courseTitle: "AH2025-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "92.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "CULTIVO DE TEJIDOS Y DIAGNOSTICO MOLECULAR",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "fe7079db-a58d-4974-9c50-e2bc5b3d10c2",
      bannerId: "28300",
      activityAcademic: "AH2001",
      courseIdentifierDisplay: "AGROECOLOGIA",
      courseNumber: "2001",
      courseReferenceNumber: "SG008",
      courseSequenceNumber: 8.0,
      courseTitle: "AH2001-MODULOS",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "AGROECOLOGIA",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "56948942-17ab-4c87-9ab9-373422ec3e14",
      bannerId: "28300",
      activityAcademic: "AGI2033",
      courseIdentifierDisplay: "AGROIN MIPYMES RURAL",
      courseNumber: "2033",
      courseReferenceNumber: "SG009",
      courseSequenceNumber: 9.0,
      courseTitle: "AGI2033-ASIGNATU",
      subject: "AGI",
      subjectDescription: "AGROINDUSTRIA ALIMENTARIA",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "100.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "AGROINDUSTRIA DE MIPYMES RURALES",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "b4148eaa-aabb-43d0-b05a-1d3b1f078265",
      bannerId: "28300",
      activityAcademic: "CG2171",
      courseIdentifierDisplay: "INGLES IV",
      courseNumber: "2171",
      courseReferenceNumber: "SG010",
      courseSequenceNumber: 10.0,
      courseTitle: "CG2171-ASIGNATU",
      subject: "CG",
      subjectDescription: "CURRICULO GENERAL",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 1.0,
      attemptedHours: 3.0,
      creditHours: 3.0,
      grade: "85.00",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "INGLES IV",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
    {
      id: "bc8e9607-d71d-46d7-8630-b50a20351320",
      bannerId: "28300",
      activityAcademic: "AH2041",
      courseIdentifierDisplay: "2041",
      courseNumber: "2041",
      courseReferenceNumber: "1273",
      courseSequenceNumber: 11.0,
      courseTitle: "APRENDER HACIENDO IV",
      subject: "AH",
      subjectDescription: "APRENDER HACIENDO",
      term: "202610",
      termDescription: "PERIODO 2026 - C1",
      studyPathSequenceNumber: 0.0,
      attemptedHours: 7.0,
      creditHours: 7.0,
      grade: "100",
      mode: "N",
      modeDescription: "CALIFICACION NUMERICA",
      sequenceNumber: 1.0,
      courseLongTitle: "APRENDER HACIENDO IV",
      levels: [
        {
          appliedLevel: "LI",
          levelDescription: "LICENCIATURA",
          primaryLevel: "Y",
        },
      ],
    },
  ],
};
